let config = {
  isHomeShope: true, /// make false when give Homeshop build for client
  isShowTaskTab: true, /// make false when give multiTenant store module build for client
  isBellPhase2: false, /// make false when give phase 2 build for client

  //// -----------------------[Ticketing bulkupload code]--------------------------------------------
  hierarchyTemplate: [
    ["Designation", "ReportTo", "Status"],
    ["HOD", "Root", "Active"],
    ["Manager", "HOD", "Active"],
  ],
  priorityTemplate: [
    ["PriorityName", "Status"],
    ["Hight", "Active"],
    ["Medium", "Active"],
    ["Low", "In-Active"],
  ],
  userTemplate: [
    [
      "UserName",
      "FirstName",
      "LastName",
      "Mobile Number",
      "User Email ID",
      "User Designation",
      "Reportee Designation",
      "Reports To",
      "CRM Role",
      "Copy Escalation",
      "Assign Escalation",
      "Escalation Agent Name",
      "Status",
    ],
    [
      "Shlok.barot",
      "Shlok",
      "Barot",
      "9665958060",
      "shlok@gmail.com",
      "Executive",
      "Manager",
      "Chetan",
      "Admin",
      "Yes",
      "Yes",
      "Vikas",
      "Active",
    ],
    [
      "Mangesh.Mishra",
      "Mangesh",
      "Mishra",
      "9665958060",
      "mangesh@gmail.com",
      "Executive",
      "Supervisor",
      "Chetan",
      "Admin",
      "Yes",
      "Yes",
      "Vikas",
      "Active",
    ],
  ],
  alertTemplate: [
    ["AlertType", "Communication Mode", "Status"],
    ["Mail", "Mail,Sms", "Active"],
    ["Agent Call", "Mail,Sms", "Active"],
  ],
  categoryTemplate: [
    ["BrandName", "Category", "SubCategory", "IssueType", "Status"],
    ["Tata", "Category-1", "SubCat-1", "IssueType-1", "Active"],
    ["Bata", "Category-2", "SubCat-2", "IssueType-2", "In-Active"],
  ],
  bulkClosureTemplate: [
    ["TicketId", "ResolutionStatus"],
    ["11281", "Customer didn't come back"],
    ["53637", "GV Points Issued"],
    ["53638", "RPU Arranged"]
  ],
  

  crmRoleTemplate: [
    ["RoleName", "Status", "EnabledModules", "DisabledModules"],
    [
      "HOD",
      "InActive",
      "Dashboard|Tickets|Knowledge Base",
      "Settings|Chat|Notification|Reports",
    ],
    [
      "Agent",
      "Active",
      "Dashboard|Tickets|Knowledge Base",
      "Settings|Chat|Notification|Reports",
    ],
  ],
  storeTemplate: [
    [
      "Brand",
      "City",
      "State",
      "PinCode",
      "StoreName",
      "Address",
      "StoreCode",
      "Region",
      "Zone",
      "StoreType",
      "StoreEmailID",
      "StorePhoneNo",
      "Status",
    ],
    [
      "Paragon",
      "Mumbai",
      "Maharashtra",
      "380001",
      "Store-Name-01",
      "Store-address-01",
      "Store-Code-01",
      "West",
      "East",
      "Commercial",
      "Store01@gmail.com",
      "909090909",
      "Active",
    ],
    [
      "BATA",
      "Ahmedabad",
      "Gujarat",
      "370001",
      "Store-Name-02",
      "Store-address-02",
      "Store-Code-02",
      "East",
      "West",
      "Retail",
      "Store02@gmail.com",
      "909090909",
      "In-Active",
    ],
  ],
  ///// ------------------------------------ [Store bulkupload code]-----------------------------------------------
  itemMasterTemplate: [
    [
      "BrandName",
      "ItemCode",
      "ItemName",
      "DepartmentName",
      "ItemCat",
      "ItemSubCategory",
      "ItemGroup",
    ],
    [
      "Amazon",
      "Item-A1",
      "Black Sneakers",
      "Casual Shoes",
      "Shoes",
      "Casual Shoes",
      "Shoes",
    ],
    [
      "Amazon",
      "Item-B1",
      "White Sneakers",
      "Casual Shoes",
      "Shoes",
      "Casual Shoes",
      "Shoes",
    ],
  ],
  claimCategoryTemplate: [
    ["BrandName", "Category", "SubCategory", "IssueType", "StatusID"],
    ["EasyRewarz", "Exchange", "Defective Article", "Broken Shoe", "Active"],
    ["EasyRewarz", "Exchange", "Defective Article", "Broken Shoe", "Active"],
  ],
  slaTemplate: [
    [
      "IssueType",
      "Priority",
      "SLABreachPercent",
      "RespondValue",
      "RespondDuration",
      "ResolutionValue",
      "ResolutionDuration",
      "Status",
    ],
    ["Issue1", "High", "30", "1", "Day", "2", "Day", "Active"],
    ["Issue1", "Medium", "30", "1", "Day", "2", "Day", "Active"],
    ["Issue1", "Low", "30", "1", "Day", "2", "Day", "Active"],
  ],
  Store_HierarchyTemplate: [
    ["Designation", "ReportTo", "Status"],
    ["HOD", "Root", "Active"],
    ["Manager", "HOD", "Active"],
  ],

  campaignTemplate: [["CampaignName", "Script"]],
  departmentTemplate: [
    ["Brand", "StoreCode", "Department", "Function", "Status"],
    ["Paragon", "TestStoreBulkasf", "Department 10", "Function10-1", "Active"],
  ],
  storeUserTemplate: [
    [
      "Brand",
      "StoreCode",
      "UserName",
      "MobileNumber",
      "UserEmailID",
      "Department",
      "Function",
      "UserDesignation",
      "ReporteeDesignation",
      "ReportsTo",
      "CRMRole",
      "Status",
      "ClaimApprover",
    ],
    [
      "Bata",
      "Store95t5",
      "abc",
      "8097654323",
      "abc@gmail.com",
      "Department-1",
      "Function-1",
      "CXO",
      "CTTO",
      "xyz",
      "Admin",
      "Active",
      "Yes",
    ],
  ],
  storeSlaTemplate: [
    [
      "FunctionType",
      "Priority",
      "SLABreachPercent",
      "ResolutionValue",
      "ResolutionDuration",
      "Status",
    ],
    ["Function1", "High", "30", "2", "Day", "Active"],
    ["Function1", "Medium", "30", "2", "Day", "Active"],
    ["Function1", "Low", "30", "2", "Day", "Active"],
  ],
  storeOrder_Template: [
    [
      "Template Name",
      "Height",
      "Length",
      "Breadth",
      "Unit",
      "Weight",
      "WeightUnit",
    ],
    ["template1", "5", "8", "5.5", "CM", "5", "KG"],
    ["template2", "6", "9", "7.5", "CM", "5", "KG"],
  ],
  slot_Template: [
    [
      "StoreCode",
      "OperationalDays",
      "TemplateName",
      "SlotStartTime",
      "SlotEndTime",
      "SlotOccupancy",
      "SlotStatus",
      "Slotdaysneedtodisplay",
      "Applicablefrom",
      "MaxPeoplePerApt",
      "DisplaySlotCode",
      "SlotSettingStatus",
    ],
    [
      "SMB3024",
      "Sunday|Monday|Tuesday|Wednesday|Thursday|Friday|Saturday",
      "Manual template 3",
      "10:00 AM",
      "10:30 AM",
      "2",
      "1",
      "10",
      "2020-12-01",
      "10",
      "302",
      "Active",
    ],
    [
      "SMB3024",
      "Sunday|Monday|Tuesday|Wednesday|Thursday|Friday|Saturday",
      "Manual template 3",
      "10:30 AM",
      "11:00 AM",
      "2",
      "1",
      "10",
      "2020-12-01",
      "10",
      "302",
      "Active",
    ],
    [
      "SMB3024",
      "Sunday|Monday|Tuesday|Wednesday|Thursday|Friday|Saturday",
      "Manual template 3",
      "6:00 PM",
      "6:30 PM",
      "2",
      "1",
      "10",
      "2020-12-01",
      "10",
      "302",
      "Active",
    ],
  ],

  lastUpdatedDate: "13-11-2021",
  appVersion: "V1.2",
  ER_MH_WhatsAppNumber: "917428849222",
  template_language: "en",
  //url: window.location.origin,
  //*******For Local**************//
  // apiUrl: "http://localhost:65167/api",
  // url:"https://multitenancyshopsterv2.dcdev.brainvire.net",
  //****************************//
  //*******For Multi Tenante*******//
  // apiUrl: "https://mts-api.dcdev.brainvire.net/Api",
  // url:"https://mts.dcdev.brainvire.net",
  //*****************************************//
  //*******For belltkt QA*******//
  apiUrl: "https://qa-api-belltkt.shopster.live/Api",
  //apiUrl: "http://127.0.0.1:43444/Api",

  url: "https://qa-ui-belltktqa.shopster.live",
  socketUrl: "https://qa-ndjs-belltkt.shopster.live/",
  // IVRSocketUrl: "https://qa-api-logticketingivr.ercx.co/",
  apiUrlsocial: "https://qa-api-socialconnector.ercx.co/api",

  //****************************//
  //*******For belltkt Live*******//
  // apiUrl: "https://api-bell.ercx.co/Api",
  //url:"https://bell.ercx.co",
  //apiUrlsocial: "https://api-socialconnector.ercx.co/api",
  //****************************//

  knowlarityAPI: "https://kpi.knowlarity.com",
  knowlarityNotificationAPI: "https://konnect.knowlarity.com",
};

export default config;
